// The old web UI had a dropdown that listed these categories. That doesn't appear to be the case anymore…
// To generate, run the following in the browser console on
// https://web.archive.org/web/20220515000031/https://play.google.com/store/apps/:
// Array.from(document.querySelectorAll('#action-dropdown-children-Categories .TEOqAc a')).reduce((acc, cur) => ({...acc, [cur.href.match(/\/([^\/]+?)$/)[1]]: cur.innerText}), {})
export const categories = {
    APPLICATION: 'Applications',
    GAME: 'Games',
    ART_AND_DESIGN: 'Art & Design',
    AUTO_AND_VEHICLES: 'Auto & Vehicles',
    BEAUTY: 'Beauty',
    BOOKS_AND_REFERENCE: 'Books & Reference',
    BUSINESS: 'Business',
    COMICS: 'Comics',
    COMMUNICATION: 'Communication',
    DATING: 'Dating',
    EDUCATION: 'Education',
    ENTERTAINMENT: 'Entertainment',
    EVENTS: 'Events',
    FINANCE: 'Finance',
    FOOD_AND_DRINK: 'Food & Drink',
    HEALTH_AND_FITNESS: 'Health & Fitness',
    HOUSE_AND_HOME: 'House & Home',
    LIBRARIES_AND_DEMO: 'Libraries & Demo',
    LIFESTYLE: 'Lifestyle',
    MAPS_AND_NAVIGATION: 'Maps & Navigation',
    MEDICAL: 'Medical',
    MUSIC_AND_AUDIO: 'Music & Audio',
    NEWS_AND_MAGAZINES: 'News & Magazines',
    PARENTING: 'Parenting',
    PERSONALIZATION: 'Personalization',
    PHOTOGRAPHY: 'Photography',
    PRODUCTIVITY: 'Productivity',
    SHOPPING: 'Shopping',
    SOCIAL: 'Social',
    SPORTS: 'Sports',
    TOOLS: 'Tools',
    TRAVEL_AND_LOCAL: 'Travel & Local',
    VIDEO_PLAYERS: 'Video Players & Editors',
    ANDROID_WEAR: 'Watch apps',
    WATCH_FACE: 'Watch faces',
    WEATHER: 'Weather',
    GAME_ACTION: 'Action',
    GAME_ADVENTURE: 'Adventure',
    GAME_ARCADE: 'Arcade',
    GAME_BOARD: 'Board',
    GAME_CARD: 'Card',
    GAME_CASINO: 'Casino',
    GAME_CASUAL: 'Casual',
    GAME_EDUCATIONAL: 'Educational',
    GAME_MUSIC: 'Music',
    GAME_PUZZLE: 'Puzzle',
    GAME_RACING: 'Racing',
    GAME_ROLE_PLAYING: 'Role Playing',
    GAME_SIMULATION: 'Simulation',
    GAME_SPORTS: 'Sports',
    GAME_STRATEGY: 'Strategy',
    GAME_TRIVIA: 'Trivia',
    GAME_WORD: 'Word',
    FAMILY: 'Kids',
} as const;

export type CategoryId = keyof typeof categories;
